swagger: "2.0"

info:
  version: 1.0.0
  title: Simple API
  description: A simple API to learn how to write OpenAPI Specification

schemes:
  - https
host: fast-campus-server-dev.herokuapp.com
basePath: /

paths:
  /auth/signup:
    post:
      summary: Used to signup new users
      description: this is the route to post all new users.  The url should contain the type of user being added while the body contains the content to be added.
      responses:
        201:
          description: The user was created successfully.  Depending on the type of user that was submited it will return the approrite type of object.  The schema provided below is a somewhat generic object that represents the bare minimum for the response.
          schema:
            type: user
              required:
                - username
              properties:
                fName:
                  type: string
                lName:
                  type: string
                username:
                  type: string
                email:
                  type: string
                school: 
                  type: string
        400:
          description: The data did not pass validation, returns array with failing items along with message and value.  This error also occurs when we try to add a user and the username already exists.
          schema:
            type: array
            items: 
              properties:
                msg:
                  type: string
                param:
                  type: string
                value: 
                  type: string
        500:
          description: The server encountered a general error while processing the request.  It will return an object err containint the errors. Because this is a catch all it is hard to define a schema for it.
          schema:
            type: array
              err: err
  /auth/login:
    post:
      summary: This is used to login
      description: This is the route that is used to login to the application.  Every user, regardless of type, should pass through this same login screen.
      responses:
        200:
          description: The data sent has resulted in a successful login. The schema shown in the response is of the generic user object.  Depending on the type of user it will respond with the approriate type of user.
          schema:
            type: user
              required:
                - username
              properties:
                fName:
                  type: string
                lName:
                  type: string
                username:
                  type: string
                email:
                  type: string
                school: 
                  type: string
        401:
          description: The data did not pass validation, returns array with failing items along with message and value.  The headers that get set are according to RFC 7235.
          schema:
            type: array
            items: 
              properties:
                msg:
                  type: string
                param:
                  type: string
                value: 
                  type: string
        500:
          description: The server encountered a general error while processing the request.  It will return an object err containint the errors. Because this is a catch all it is hard to define a schema for it.
          schema:
            type: array
              err: err
  /student:
    patch:
      summary: This is used to update the student
      description: This method is used to update a particular student by id.  It expects the id and fields that need updated in the body.
      responses:
        200:
          description: The user has been updated.
          schema:
            type: user
              properties:
                fName:
                  type: string
                lName:
                  type: string
                username:
                  type: string
                email:
                  type: string
                school: 
                  type: string
        400:
          description: The data did not pass validation, returns array with failing items along with message and value.  This error also occurs when we try to add a user and the username already exists.
          schema:
            type: array
            items: 
              properties:
                msg:
                  type: string
                param:
                  type: string
                value: 
                  type: string
        500:
          description: The server encountered a general error while processing the request.  It will return an object err containint the errors. Because this is a catch all it is hard to define a schema for it.
          schema:
            type: array
              err: err
    delete:
      summary: Used to delete the student
      description: This method is used to delete the student object fromt the db.  This is not reverisble.
      responses:
        200:
          description: The student has been successfully deleted
          schema:
            msg: string
        500:
          description: The server encountered a general error while processing the request.  It will return an object err containint the errors. Because this is a catch all it is hard to define a schema for it.
          schema:
            type: array
              err: err
  /tutor:
    get:
      summary: Get tutors from the db
      description: This method is used to query the db
      responses:
        200:
          description: successful query, returns an array of tutors 
          schema:
            type: tutor
              properties:
                fName:
                  type: string
                lName:
                  type: string
                username:
                  type: string
                email:
                  type: string
                school: 
                  type: string
                pNmber: 
                  type: string
                passwordResetToken:
                  type: string
                passwordResetExpires:
                  type: date
                courses:
                  type: array
                  items:
                    properties:
                      number: 
                        type: number
                      name:
                        type: string
                available:
                  type: array
                  items:
                    day:
                      type: string
                    hours: array
                      type: string
                office:
                  type: office
                    properties:
                      building: 
                        type: string
                      roomNumber:
                        type: string
        500:
          description: The server encountered a general error while processing the request.  It will return an object err containint the errors. Because this is a catch all it is hard to define a schema for it.
          schema:
            type: array
              err: err
    post:
      summary: Add tutor to db
      description: This method is used to add a tutor to the db.
      responses:
        201:
          description: The tutor was created successfully. 
          schema:
            type: tutor
              properties:
                fName:
                  type: string
                lName:
                  type: string
                username:
                  type: string
                email:
                  type: string
                school: 
                  type: string
                pNmber: 
                  type: string
                passwordResetToken:
                  type: string
                passwordResetExpires:
                  type: date
                courses:
                  type: array
                  items:
                    properties:
                      number: 
                        type: number
                      name:
                        type: string
                available:
                  type: array
                  items:
                    day:
                      type: string
                    hours: array
                      type: string
                office:
                  type: office
                    properties:
                      building: 
                        type: string
                      roomNumber:
                        type: string
        400:
          description: The data did not pass validation, returns array with failing items along with message and value.  This error also occurs when we try to add a user and the username already exists.
          schema:
            type: array
            items: 
              properties:
                msg:
                  type: string
                param:
                  type: string
                value: 
                  type: string
        500:
          description: The server encountered a general error while processing the request.  It will return an object err containint the errors. Because this is a catch all it is hard to define a schema for it.
          schema:
            type: array
              err: err
    patch:
      summary: This is used to update the tutor
      description: This method is used to update a particular tutor by id.  It expects the id and fields that need updated in the body.
      responses:
        200:
          description: The user has been updated.
          schema:
            type: tutor
              properties:
                fName:
                  type: string
                lName:
                  type: string
                username:
                  type: string
                email:
                  type: string
                school: 
                  type: string
                pNmber: 
                  type: string
                passwordResetToken:
                  type: string
                passwordResetExpires:
                  type: date
                courses:
                  type: array
                  items:
                    properties:
                      number: 
                        type: number
                      name:
                        type: string
                available:
                  type: array
                  items:
                    day:
                      type: string
                    hours: array
                      type: string
                office:
                  type: office
                    properties:
                      building: 
                        type: string
                      roomNumber:
                        type: string
        400:
          description: The data did not pass validation, returns array with failing items along with message and value.  This error also occurs when we try to add a user and the username already exists.
          schema:
            type: array
            items: 
              properties:
                msg:
                  type: string
                param:
                  type: string
                value: 
                  type: string
        500:
          description: The server encountered a general error while processing the request.  It will return an object err containint the errors. Because this is a catch all it is hard to define a schema for it.
          schema:
            type: array
              err: err
    delete:
      summary: Used to delete the tutor
      description: This method is used to delete the tutor object fromt the db.  This is not reverisble.
      responses:
        200:
          description: The tutor has been successfully deleted
          schema:
            msg: string
        500:
          description: The server encountered a general error while processing the request.  It will return an object err containint the errors. Because this is a catch all it is hard to define a schema for it.
          schema:
            type: array
              err: err
  /course:
    get:
      summary: Get courses from the db
      description: This method is used to query the db
      responses:
        200:
          description: successful query, returns an array of courses 
          schema:
            type: course
              properties:
                subject:
                  type: string
                number:
                  type: string
                name:
                  type: string
                sections: 
                  type: array
                    properties:
                      crnNumber:
                        type: string
                      sectionNumber:
                        type: string
                      time:
                        type: string
                      professor:
                        type: string
        500:
          description: The server encountered a general error while processing the request.  It will return an object err containint the errors. Because this is a catch all it is hard to define a schema for it.
          schema:
            type: array
              err: err
    post:
      summary: Add course to db
      description: This method is used to add a course to the db.
      responses:
        200:
          description: successful query, returns an array of courses 
          schema:
            type: course
              properties:
                subject:
                  type: string
                number:
                  type: string
                name:
                  type: string
                sections: 
                  type: array
                    properties:
                      crnNumber:
                        type: string
                      sectionNumber:
                        type: string
                      time:
                        type: string
                      professor:
                        type: string
        400:
          description: The data did not pass validation, returns array with failing items along with message and value.  This error also occurs when we try to add a user and the username already exists.
          schema:
            type: array
            items: 
              properties:
                msg:
                  type: string
                param:
                  type: string
                value: 
                  type: string
        500:
          description: The server encountered a general error while processing the request.  It will return an object err containint the errors. Because this is a catch all it is hard to define a schema for it.
          schema:
            type: array
              err: err
    patch:
      summary: This is used to update the tutor
      description: This method is used to update a particular course by id.  It expects the id and fields that need updated in the body.
      responses:
        200:
          description: successful query, returns an array of courses 
          schema:
            type: course
              properties:
                subject:
                  type: string
                number:
                  type: string
                name:
                  type: string
                sections: 
                  type: array
                    properties:
                      crnNumber:
                        type: string
                      sectionNumber:
                        type: string
                      time:
                        type: string
                      professor:
                        type: string
        400:
          description: The data did not pass validation, returns array with failing items along with message and value.  This error also occurs when we try to add a user and the username already exists.
          schema:
            type: array
            items: 
              properties:
                msg:
                  type: string
                param:
                  type: string
                value: 
                  type: string
        500:
          description: The server encountered a general error while processing the request.  It will return an object err containint the errors. Because this is a catch all it is hard to define a schema for it.
          schema:
            type: array
              err: err
    delete:
      summary: Used to delete the course
      description: This method is used to delete the course object fromt the db.  This is not reverisble.
      responses:
        200:
          description: The course has been successfully deleted
          schema:
            msg: string
        500:
          description: The server encountered a general error while processing the request.  It will return an object err containint the errors. Because this is a catch all it is hard to define a schema for it.
          schema:
            type: array
              err: err